// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
// Load the shared .env (resolved from the cwd, which is this package's
// directory when Prisma CLI commands run). `../.env` is kept last as a fallback
// for the old monorepo layout where this package lived in a `frontend/` subdir.
loadEnv({ path: [".env.local", ".env", "../.env"] });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
